# Generated by Django 3.2 on 2021-04-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория товара',
                'verbose_name_plural': 'Категории товара',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('group', models.CharField(max_length=255, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('bar_code', models.BigIntegerField(verbose_name='Штрих-код')),
                ('vendor_code', models.CharField(max_length=255, verbose_name='Артикул')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('details', models.CharField(max_length=255, verbose_name='Характеристика товара')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.category', verbose_name='Категория')),
                ('storage', models.ManyToManyField(to='ics.Storage', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
