# Generated by Django 3.2 on 2021-04-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='slug',
            field=models.SlugField(default='hi', unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
