# Generated by Django 3.2 on 2021-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='amount_available',
            field=models.IntegerField(default=0, verbose_name='Количество доступных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='amount_booked',
            field=models.IntegerField(default=0, verbose_name='Количество забронированных'),
        ),
    ]
